In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install keras scikit-learn imbalanced-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
pip install --upgrade scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

df = pd.read_csv("/content/drive/MyDrive/Dataset TA/DATASET GABUNGAN REVISI 20230126.csv", sep=';', header=0)
print(df)

         PIR 1  PIR 2  PIR 3  PIR 4  Target
0            1      0      0      0       1
1            0      1      0      0       2
2            0      0      0      0       0
3            0      0      0      0       0
4            0      0      0      0       0
...        ...    ...    ...    ...     ...
1044510      0      0      0      0       0
1044511      0      0      0      0       0
1044512      0      0      0      0       0
1044513      0      0      0      0       0
1044514      0      0      0      0       0

[1044515 rows x 5 columns]


In [ ]:
X = df.iloc[:, [0,1,2,3]].values
y = df. iloc [:, -1].values
print("Matrix of features", X, sep='\n')
print("--------------------------------------------------")
print("Target Variable", y, sep='\n')

Matrix of features
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
--------------------------------------------------
Target Variable
[1 2 0 ... 0 0 0]


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.30, 
                                                    random_state=1)

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt

# Fit the SVC model
#
svc = SVC(kernel='linear', C=10.0, random_state=1)
svc.fit(X_train, y_train)
#
# Get the predictions
#
y_pred = svc.predict(X_test)

print('Precision: %.3f' % precision_score(y_test, y_pred, average='micro'))
print('Recall: %.3f' % recall_score(y_test, y_pred, average='micro'))
print('F1 Score: %.3f' % f1_score(y_test, y_pred, average='micro'))

Precision: 1.000
Recall: 1.000
F1 Score: 1.000


### Bagged Decision Tree classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier

cv = KFold(n_splits=10)
estimator = DecisionTreeClassifier()
model = BaggingClassifier(base_estimator=estimator, n_estimators=100)
score = cross_val_score(model, X_train, y_train, cv=cv)


model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(score.mean())
print('Precision: %.3f' % precision_score(y_test, y_pred, average='micro'))
print('Recall: %.3f' % recall_score(y_test, y_pred, average='micro'))
print('F1 Score: %.3f' % f1_score(y_test, y_pred, average='micro'))

0.999903065013072
Precision: 1.000
Recall: 1.000
F1 Score: 1.000


### Boosting

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

cv = KFold(n_splits=10)
model = AdaBoostClassifier(n_estimators=150, learning_rate=0.1)
score = cross_val_score(model, X_train, y_train, cv=cv)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(score.mean())
print('Precision: %.3f' % precision_score(y_test, y_pred, average='micro'))
print('Recall: %.3f' % recall_score(y_test, y_pred, average='micro'))
print('F1 Score: %.3f' % f1_score(y_test, y_pred, average='micro'))

0.9998994748357969
Precision: 1.000
Recall: 1.000
F1 Score: 1.000


### Stacking

In [ ]:
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import VotingClassifier

cv = KFold(n_splits=10)

models = []
models.append(('xgb', XGBClassifier(n_estimators=150)))
models.append(('svc', SVC()))
models.append(('extra', ExtraTreesClassifier(n_estimators=100, max_features=3)))

model = VotingClassifier(models)
score = cross_val_score(model, X_train, y_train, cv=cv)

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(score.mean())
print('Precision: %.3f' % precision_score(y_test, y_pred, average='micro'))
print('Recall: %.3f' % recall_score(y_test, y_pred, average='micro'))
print('F1 Score: %.3f' % f1_score(y_test, y_pred, average='micro'))

0.9999018682825399
Precision: 1.000
Recall: 1.000
F1 Score: 1.000
